### ISSUE TITLE
Figure out a project 

### ISSUE THREAD

**Issue by GoodZombie** [GoodZombie/Roommate-Rate#1]
We gotta have an project throw any ideas into this.

**Comment by Whitehawk2015** [comment]
I had an idea for a product for UNA. It would basically build on the roommate system currently in place by allowing students to review their roommates at the end of the semester. This could be added to their anonymous roommate profile to make it easier to find new roommates. It would also help the university pair up bad roommates to allow better ones an opportunity to avoid them.

The current system allows students to fill out a self survey which tends to be very inaccurate. The new system would allow them to be judged by someone who has experienced life with them.

**Comment by Whitehawk2015** [comment]
[Roommate-Questionnaire.pdf](https://github.com/GoodZombie/Roommate-Rate/files/7219704/Roommate-Questionnaire.pdf)
